# Generated by Django 3.1.2 on 2020-11-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='webtoken',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
