from rest_framework.views import APIView
from rest_framework.response import Response

# Analysis file generated by Java Mag Analyzer created by Rafał Senetra
ANALYSIS_PATH = 'http://192.168.1.40/Analiza%20min%20(25%25%20zapas)%20(wstecz).xls'

class AnalysisReader():
    data = list()
    def __init__(self):
        self.read_analysis()
    
    def read_analysis(self):
        """ Reads analysis xls file from server """
        import xlrd
        import requests
        r = requests.get(ANALYSIS_PATH)
        analysis = xlrd.open_workbook(file_contents=r.content)
        sheet = analysis.sheet_by_index(0)
        for row in range(2, sheet.nrows):
            self.data.append(sheet.row_values(row))


class MagAnalyzer(APIView):
    """ Class that connects products with stock xls analysis on 192.168.1.40 server. """
    def get(self, request, ean):
        analysis_reader = AnalysisReader()
        product_analysis = self.search_for_analysis(ean, analysis_reader.data)
        return Response(product_analysis, content_type='application/json')
    
    def search_for_analysis(self, ean, analysis):
        """ Returns first analysis for given ean """
        return next((x for x in analysis if x[14] == ean), None)