# Generated by Django 3.1.2 on 2021-06-18 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grafik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nazwa', models.CharField(max_length=200, null=True)),
                ('Author', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GrafikPracownik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Imie_i_nazwisko', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GrafikGrupa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nazwa', models.CharField(max_length=200, null=True)),
                ('Pracownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plancreator.grafikpracownik')),
            ],
        ),
        migrations.CreateModel(
            name='GrafikDzien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dzien_miesiaca', models.IntegerField()),
                ('Czy_pracuje', models.BooleanField(default=False)),
                ('Godz_pracy', models.CharField(max_length=20, null=True)),
                ('Grafik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plancreator.grafik')),
                ('Pracownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plancreator.grafikpracownik')),
            ],
        ),
    ]
