# Generated by Django 3.1.2 on 2021-07-08 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plancreator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grafikgrupa',
            name='Pracownik',
        ),
        migrations.AddField(
            model_name='grafikpracownik',
            name='Grupa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='plancreator.grafikgrupa'),
            preserve_default=False,
        ),
    ]
