# Generated by Django 3.1.2 on 2021-07-26 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plancreator', '0002_auto_20210708_0816'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrafikZmiana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nazwa', models.CharField(max_length=50, null=True)),
                ('Godz_pracy', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='grafikdzien',
            name='Godz_pracy',
        ),
        migrations.AddField(
            model_name='grafikdzien',
            name='Zmiana',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='plancreator.grafikzmiana'),
            preserve_default=False,
        ),
    ]
