# Generated by Django 3.1.2 on 2021-07-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plancreator', '0003_auto_20210726_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grafikdzien',
            name='Dzien_miesiaca',
        ),
        migrations.AddField(
            model_name='grafikdzien',
            name='Dzien',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='grafikdzien',
            name='Miesiac',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='grafikdzien',
            name='Rok',
            field=models.IntegerField(null=True),
        ),
    ]
