# Generated by Django 3.1.2 on 2021-08-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plancreator', '0004_auto_20210727_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='grafikpracownik',
            name='Czy_niepelnosprawny',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
