# Generated by Django 3.1.2 on 2021-08-24 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plancreator', '0005_grafikpracownik_czy_niepelnosprawny'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grafikpracownik',
            name='Czy_niepelnosprawny',
            field=models.BooleanField(default=False),
        ),
    ]
