# Generated by Django 3.1.2 on 2021-10-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plancreator', '0006_auto_20210824_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='grafikgrupa',
            name='Algorytm',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
