# Generated by Django 3.1.2 on 2020-11-30 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supermagazynier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Author', models.IntegerField()),
                ('Title', models.CharField(default='default', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VerifyProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Index', models.CharField(max_length=40, unique=True)),
                ('Quantity', models.IntegerField()),
                ('Document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermagazynier.verifydocument')),
            ],
        ),
    ]
