# Generated by Django 3.1.2 on 2021-02-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermagazynier', '0004_auto_20210113_0922'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.IntegerField()),
                ('Tag', models.CharField(max_length=50)),
            ],
        ),
    ]
