# Generated by Django 3.1.2 on 2021-04-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermagazynier', '0005_favouritetags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifyproducts',
            name='Index',
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
