# Generated by Django 3.1.2 on 2022-03-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermagazynier', '0008_auto_20220309_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifyproducts',
            name='Unit',
            field=models.CharField(default='', max_length=20),
        ),
    ]
