# Generated by Django 3.1.2 on 2022-05-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermagazynier', '0010_verifydocument_correctness'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifyproducts',
            name='Price',
            field=models.FloatField(default=0, null=True),
        ),
    ]
