# Generated by Django 3.1.2 on 2022-06-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermagazynier', '0011_verifyproducts_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifydocument',
            name='Title',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AlterField(
            model_name='verifyproducts',
            name='Index',
            field=models.CharField(max_length=70),
        ),
    ]
