# Generated by Django 3.1.2 on 2022-06-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermagazynier', '0012_auto_20220630_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifydocument',
            name='Title',
            field=models.CharField(default='default', max_length=50, unique=True),
        ),
    ]
