# Generated by Django 3.1.2 on 2022-06-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermagazynier', '0013_auto_20220630_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifyproducts',
            name='ProductId',
            field=models.IntegerField(default=0),
        ),
    ]
