# Generated by Django 3.1.2 on 2022-09-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermagazynier', '0014_verifyproducts_productid'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelPrinters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Exec_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.IntegerField()),
                ('Label_printer', models.IntegerField()),
            ],
        ),
    ]
