# Generated by Django 3.1.2 on 2022-10-31 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermagazynier', '0015_labelprinters_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifydocument',
            name='Creation_date',
            field=models.CharField(default='', max_length=50),
        ),
    ]
